// Generated by Diesel CLI
diesel::table! {
    users (id) {
        id -> Uuid,
        email -> Varchar,
        password_hash -> Varchar,
        name -> Nullable<Varchar>,
        avatar_url -> Nullable<Varchar>,
        created_at -> Timestamp,
    }
}

diesel::table! {
    projects (id) {
        id -> Uuid,
        owner_id -> Uuid,
        name -> Varchar,
        description -> Nullable<Text>,
        created_at -> Timestamp,
        updated_at -> Timestamp,
    }
}

diesel::table! {
    branches (id) {
        id -> Uuid,
        project_id -> Uuid,
        name -> Varchar,
        created_at -> Timestamp,
    }
}

diesel::table! {
    commits (id) {
        id -> Uuid,
        branch_id -> Uuid,
        author_id -> Uuid,
        message -> Text,
        created_at -> Timestamp,
    }
}

diesel::table! {
    blobs (id) {
        id -> Uuid,
        commit_id -> Uuid,
        file_path -> Varchar,
        content -> Bytea,
    }
}

diesel::table! {
    comments (id) {
        id -> Uuid,
        commit_id -> Uuid,
        author_id -> Uuid,
        content -> Text,
        created_at -> Timestamp,
    }
}

diesel::table! {
    nfts (id) {
        id -> Uuid,
        project_id -> Uuid,
        creator_id -> Uuid,
        token_id -> Nullable<Varchar>,
        contract_address -> Nullable<Varchar>,
        metadata_uri -> Varchar,
        title -> Varchar,
        description -> Nullable<Text>,
        price -> Nullable<Numeric>,
        royalty_percentage -> Numeric,
        is_minted -> Bool,
        is_listed -> Bool,
        opensea_url -> Nullable<Varchar>,
        created_at -> Timestamp,
        updated_at -> Timestamp,
    }
}

diesel::table! {
    collaborations (id) {
        id -> Uuid,
        project_id -> Uuid,
        user_id -> Uuid,
        contribution_percentage -> Numeric,
        role -> Varchar,
        joined_at -> Timestamp,
    }
}

diesel::table! {
    revenue_shares (id) {
        id -> Uuid,
        nft_id -> Uuid,
        user_id -> Uuid,
        percentage -> Numeric,
        amount_earned -> Nullable<Numeric>,
        created_at -> Timestamp,
    }
}

diesel::joinable!(projects -> users (owner_id));
diesel::joinable!(branches -> projects (project_id));
diesel::joinable!(commits -> branches (branch_id));
diesel::joinable!(commits -> users (author_id));
diesel::joinable!(comments -> commits (commit_id));
diesel::joinable!(comments -> users (author_id));
diesel::joinable!(blobs -> commits (commit_id));
diesel::joinable!(nfts -> projects (project_id));
diesel::joinable!(nfts -> users (creator_id));
diesel::joinable!(collaborations -> projects (project_id));
diesel::joinable!(collaborations -> users (user_id));
diesel::joinable!(revenue_shares -> nfts (nft_id));
diesel::joinable!(revenue_shares -> users (user_id));

diesel::allow_tables_to_appear_in_same_query!(
    users,
    projects,
    branches,
    commits,
    blobs,
    comments,
    nfts,
    collaborations,
    revenue_shares,
);